version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: route-scheduling-db
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: route_scheduling
    ports:
      - "27018:27017" 
    volumes:
      - mongodb_data:/data/db
    restart: unless-stopped

  app:
    build: .
    container_name: route-scheduling-app
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - MONGODB_URI=mongodb://admin:password@mongodb:27017/route_scheduling?authSource=admin
    depends_on:
      - mongodb
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    command: npm run dev

volumes:
  mongodb_data:
